function ParameterRange = GetParameterRanges(ParameterLabel)
    % Define a map of predefined parameter ranges
    predefinedRanges = struct(...
        'Kappa', [0, 0.33], ...
        'K1Circ', [0, -0.2], ...
        'K2Circ', [0, -0.2], ...
        'K1Rad', [0, -0.2], ...
        'K2Rad', [0, -0.2], ...
        'Lambda', [0.3, 2], ...
        'LambdaRad', [0, -0.2], ...
        'LambdaCirc', [0, -0.2], ...
        'FiberAngleRad', [0, 0.2], ...
        'FiberAngleCirc', [0, 0.3], ...
        'FiberPoissonRate', [0.3, 0.49] ...
    );

    % Check if the parameter is predefined
    if isfield(predefinedRanges, ParameterLabel)
        ParameterRange = predefinedRanges.(ParameterLabel);
    else
        % Read values from the txt file
        filename = ['./MaterialParameter/', ParameterLabel, '.txt'];
        fid = fopen(filename);
        if fid == -1
            error(['File not found: ', filename]);
        end
        ParameterData = textscan(fid, '%f # %[^\n]', 'HeaderLines', 0);
        fclose(fid);
        ParameterValues = ParameterData{1};
        ParameterMedian = round(median(ParameterValues), 2);
        ParameterRange = [0.5 * ParameterMedian, 1.5 * ParameterMedian];
    end
end